theme: jekyll-theme-slate
title: The Bristol Stool Chart mobile app for iOS and Android
description: Easily chart your stools against the Bristol Stool Scale. Track, export and share your progress with your medical professional. Monitor your bowel health now.