include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test_driver/**
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
