name: bristol_stool_chart
description: A simple to use app for tracking your stool quality over time.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  intro_slider: ^3.0.3

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
