name: bristol_stool_chart
description: A simple to use app for tracking your stool quality and intestinal health.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.7+27

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^7.7.0
  carousel_slider: ^4.2.1
  cross_file: ^0.3.3+4
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.0.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  intro_slider: ^4.2.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  sembast: ^3.4.9
  shared_preferences: ^2.2.0
  share_plus: ^7.0.2
  sprintf: ^7.0.0
  sqflite: ^2.2.8+4
  syncfusion_flutter_charts: ^22.1.37
  url_launcher: ^6.1.12

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: FontAwesome5Free
      fonts:
        - asset: assets/fonts/FontAwesome5Free-Regular-400.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
