name: bristol_stool_chart
description: A simple to use app for tracking your stool quality and intestinal health.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.2+19

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  carousel_slider: ^4.0.0
  dartz: ^0.10.1
  date_time_picker: ^2.1.0
  flutter:
    sdk: flutter
  freezed: ^1.1.1
  google_fonts: ^2.2.0
  hooks_riverpod: ^1.0.3
  intl: ^0.17.0
  intro_slider: ^3.0.3
  path_provider: ^2.0.9
  sembast: ^3.1.2
  shared_preferences: ^2.0.12
  share_plus: ^3.1.0
  syncfusion_flutter_charts: ^19.4.48+1
  url_launcher: ^6.0.20

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/
    - assets/images/
  fonts:
    - family: FontAwesome5Free
      fonts:
        - asset: assets/fonts/FontAwesome5Free-Regular-400.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
