name: bristol_stool_chart
description: A simple to use app for tracking your stool quality over time.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed: ^1.1.1
  google_fonts: ^2.2.0
  hooks_riverpod: ^1.0.3
  intro_slider: ^3.0.3
  sembast: ^3.1.2
  shared_preferences: ^2.0.12
  syncfusion_flutter_charts: ^19.4.48+1

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.4

flutter:
  assets:
    - assets/images/
    - google_fonts/
  uses-material-design: true
