name: bristol_stool_chart
description: A simple to use app for tracking your stool quality and intestinal health.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.8+28

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  carousel_slider: ^5.0.0
  cross_file: ^0.3.3
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.5
  freezed_annotation: ^2.4.4
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.10
  intl: ^0.19.0
  intro_slider: ^4.2.1
  json_annotation: 4.9.0
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.1.2
  sembast: ^3.6.0
  shared_preferences: ^2.2.3
  share_plus: ^7.2.2
  sprintf: ^7.0.0
  sqflite: ^2.3.0
  syncfusion_flutter_charts: ^26.2.11
  url_launcher: ^6.1.0

dev_dependencies:
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: FontAwesome5Free
      fonts:
        - asset: assets/fonts/FontAwesome5Free-Regular-400.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
